import { taxBySalaryRows } from "./taxBySalary";

export interface GuideTable {
  /** Render the table right after body[afterIndex]. */
  afterIndex: number;
  caption: string;
  headers: string[];
  rows: string[][];
}

export interface Guide {
  slug: string;
  title: string;
  description: string;
  publishedDate: string;
  body: string[];
  table?: GuideTable;
  faq?: { q: string; a: string }[];
  relatedLinks?: { href: string; label: string }[];
}

export const GUIDES: Guide[] = [
  {
    slug: "how-bonuses-are-taxed-in-malaysia",
    title: "How Bonuses Are Actually Taxed in Malaysia",
    description: "Your bonus isn't taxed at a special higher rate — here's what really happens to it, and why a big bonus month can shrink your usual paycheck.",
    publishedDate: "2026-01-15",
    body: [
      "A lot of Malaysian employees open their bonus-month payslip, see a much bigger PCB deduction than usual, and assume bonuses are taxed at some punishing special rate. They aren't. There's no separate 'bonus tax bracket' in Malaysia — a bonus is just ordinary employment income, and it's taxed using the exact same progressive rates as your salary.",
      "## Why the deduction looks so much bigger",
      "The confusion comes from how PCB is withheld, not from a different tax rate. When your employer processes a bonus, LHDN's formula method treats it as 'additional remuneration': it works out your tax for the whole year assuming you never got the bonus, then works out your tax for the whole year including it, and withholds the entire difference in that single month. Spread over twelve months, your effective tax rate on the bonus is exactly the same as on your regular salary — it's just collected all at once instead of gradually.",
      "## EPF still applies to bonuses",
      "Under the EPF Act's definition of wages, a bonus counts as remuneration, so it's subject to EPF just like your normal pay — both your and your employer's share. This is different from SOCSO and EIS, where bonuses, gratuities and retirement benefits are explicitly excluded from the wage definition used to calculate contributions.",
      "## Does the timing of a bonus matter?",
      "Not for how much tax you eventually owe over the year — your total annual tax is the same whether a bonus arrives in January or December. What does change is your cash flow: a large bonus concentrated in one month means a large PCB deduction that same month, which can catch people off guard if they've already budgeted the gross amount.",
      "## A quick way to sanity-check your bonus payslip",
      "If your bonus month's PCB looks unusually high, it's worth separating the two questions: was the withholding correct given your annual income, or is your total annual tax burden itself high? The first is usually just the mechanics of the formula method working as designed. The second is a real reflection of your income level and reliefs claimed — which is exactly what our full salary calculator's one-off bonus toggle is built to show you before payday, not after.",
    ],
    relatedLinks: [
      { href: "/bonus-calculator", label: "Bonus Tax Calculator" },
      { href: "/pcb-calculator", label: "PCB Calculator (MTD)" },
    ],
  },
  {
    slug: "annual-tax-relief-checklist",
    title: "Your Annual Tax Relief Checklist Before You File",
    description: "A practical, no-nonsense rundown of the reliefs most working Malaysians can claim — and the receipts you should be keeping right now.",
    publishedDate: "2026-02-03",
    body: [
      "Tax relief season tends to sneak up on people. The frustrating part isn't the filing itself — it's realising in March that you didn't keep a receipt for something you were entitled to claim eleven months earlier. Here's a practical checklist to run through during the year, not just at filing time.",
      "## Reliefs that apply automatically",
      "Your individual relief and your EPF/SOCSO-EIS contribution reliefs don't need any extra paperwork from you — they're based on amounts your employer already reports. If you're married and your spouse doesn't have their own income, spousal relief is similarly straightforward, though it does need to be claimed correctly in your assessment.",
      "## Reliefs that need receipts you probably already have",
      "Lifestyle relief covers a surprisingly broad basket: books, computers and smartphones, internet subscriptions, and sporting equipment or gym memberships. Most people qualify for at least part of this without trying — the trick is just not deleting the e-receipt. Medical expense relief for serious conditions, fertility treatment, or a general health check-up (capped separately within the medical relief) is another one where keeping the clinic's official receipt, not just a payment notification, matters.",
      "## Reliefs that need a bit of planning",
      "Life insurance and takaful premiums, EPF voluntary top-ups, SSPN education savings deposits, and parental medical or care expenses are all reliefs where the amount you can claim is directly tied to how much you actually paid in during the year — meaning there's a real, calculable benefit to reviewing your contributions before the year closes, not after.",
      "## Don't forget dependents",
      "Child relief scales with your child's age and education status, and disabled-individual relief (for yourself, your spouse, or a child) is often under-claimed simply because people don't realise they qualify or forget to register the required OKU documentation with the relevant authority in time.",
      "## Where this calculator fits in",
      "Our PCB calculator lets you plug in the reliefs you expect to claim and see the effect on your monthly tax deduction immediately, rather than waiting for your annual filing to find out. It's not a substitute for LHDN's official relief list — always check the current year's gazette or MyTax portal for the definitive figures — but it's a fast way to see whether a relief you're planning to claim is actually worth adjusting your finances around.",
    ],
    relatedLinks: [
      { href: "/pcb-calculator", label: "PCB Calculator (MTD)" },
      { href: "/", label: "Full Salary Calculator" },
    ],
  },
  {
    slug: "minimum-wage-updates-malaysia",
    title: "Minimum Wage in Malaysia: What's Changed and What It Affects",
    description: "A plain-language look at how Malaysia's minimum wage policy works, who it covers, and how it ripples into EPF and SOCSO contributions.",
    publishedDate: "2026-09-20",
    body: [
      "Malaysia's minimum wage is set nationally and applies to almost all employees, with a specific carve-out historically given to smaller employers on a delayed timeline. It's reviewed periodically, and when it changes, the ripple effects go beyond just the headline number.",
      "## The current RM1,700 rate is under active review",
      "As of August 2026, the government has publicly confirmed it is reviewing the current RM1,700 monthly minimum wage, with a possible increase under discussion based on factors like cost of living and wage levels. This isn't a confirmed new figure yet — just an active review — and Malaysia's minimum wage is set to be revisited on a roughly two-year cycle, so a review at this point in the cycle isn't unusual. If you're budgeting payroll costs for the coming year, this is worth watching rather than acting on, since nothing changes until an actual gazetted rate is announced.",
      "## It's not just about the paycheck",
      "Because EPF, SOCSO and EIS contributions are all calculated as a percentage (or banded amount) of wages, any minimum wage increase automatically increases the statutory contributions tied to it too — both what the employee sees deducted and what the employer has to budget for on top. A minimum wage worker's real 'cost to the company' has always been noticeably higher than their gross pay alone once you add the employer's EPF, SOCSO and EIS shares.",
      "## Who's actually covered",
      "The minimum wage applies to employees under a contract of service, full-time or part-time (with part-time wages typically pro-rated by hours worked against the full-time monthly figure). It does not apply to domestic workers, who are covered by separate arrangements, and generally does not apply to genuine independent contractors who aren't legally 'employees' in the first place.",
      "## Why this matters even if you earn well above minimum wage",
      "Minimum wage changes often trigger a broader compression effect: employers reviewing pay bands for their lowest-paid staff frequently end up adjusting adjacent bands too, to preserve pay differentials for more senior or experienced roles. If you're a small business owner budgeting headcount costs, or an HR professional building next year's pay bands, it's worth treating a minimum wage announcement as a prompt to re-check your full pay structure, not just your lowest tier.",
      "## Checking today's figure",
      "Because this is a policy figure that changes with government announcements rather than a fixed formula, always confirm the current gazetted amount directly from the Ministry of Human Resources before using it for payroll decisions — our rate-changes page tracks the figure we've verified for the current and previous year, but a policy change can happen between our review cycles.",
    ],
    relatedLinks: [
      { href: "/", label: "Full Salary Calculator" },
      { href: "/hourly-rate-calculator", label: "Hourly & Daily Rate Calculator" },
    ],
  },
  {
    slug: "understanding-employment-act-overtime-rules",
    title: "Understanding Overtime Rules Under the Employment Act",
    description: "Normal day, rest day, or public holiday — the multiplier you're owed depends entirely on which one applies, and most people only know the first.",
    publishedDate: "2026-04-22",
    body: [
      "Ask most employees what overtime pays, and you'll get one answer: time-and-a-half. That's correct for a normal working day — but it's only a third of the picture. The Employment Act 1955 sets out three distinct overtime scenarios, and mixing them up is one of the most common payroll mistakes we see referenced in employment disputes.",
      "## The three scenarios",
      "On a normal working day, overtime is straightforward: 1.5 times your hourly rate for every hour worked beyond your normal hours. On a rest day, the calculation depends on how much of the day you actually worked — half a day's wages if you worked up to half your normal hours, a full day's wages if you worked up to a full normal day, and a full day's wages plus double your hourly rate for anything beyond that. Public holidays are the most generous: two full days' wages just for working up to your normal hours, plus triple your hourly rate for any excess.",
      "## Getting your hourly rate right first",
      "Every one of these calculations depends on your 'ordinary rate of pay' — typically your monthly salary divided by 26 working days, then divided again by your normal daily hours. Getting this base figure wrong (using 30 days instead of 26, for instance) throws off every overtime calculation that follows it, even if you apply the right multiplier afterward.",
      "## Who's actually covered",
      "These specific statutory multipliers are guaranteed to employees covered by the Employment Act's First Schedule — currently those earning RM4,000 a month or less, plus any manual labourer or machinery operator regardless of salary. If you earn above that threshold and aren't in a covered category, your overtime entitlement comes from your employment contract instead, which may match, exceed, or fall short of the statutory rates — so it's always worth checking your contract's actual wording rather than assuming the Act applies.",
      "## A common mistake worth flagging",
      "Some employers calculate all overtime — regardless of day type — at the normal-day 1.5x rate. If you've worked a rest day or public holiday, that likely underpays you relative to the statutory formula. Running the numbers through a dedicated calculator before raising it with HR is usually the fastest way to have a productive, fact-based conversation instead of a guessing match.",
    ],
    relatedLinks: [
      { href: "/overtime-calculator", label: "Overtime Pay Calculator" },
      { href: "/hourly-rate-calculator", label: "Hourly & Daily Rate Calculator" },
      { href: "/annual-leave-calculator", label: "Annual Leave Calculator" },
    ],
  },
  {
    slug: "epf-withdrawal-rules-malaysia",
    title: "EPF Withdrawal Rules: What You Can Take Out Early",
    description: "Your EPF savings aren't fully locked until 55 — here's exactly which accounts you can tap into earlier, and under what conditions.",
    publishedDate: "2026-09-20",
    body: [
      "Most people think of EPF as one lump sum that unlocks at retirement age and stays sealed until then. In practice, your contributions are split across three accounts with different rules, and several withdrawal schemes let you access money well before 55 — provided you meet the specific conditions for each one.",
      "## The three-account split (since May 2024)",
      "EPF restructured from two accounts to three, effective 11 May 2024. Every contribution now splits into Akaun Persaraan (75%, formerly Account 1 — long-term retirement savings, the hardest to withdraw early), Akaun Sejahtera (15%, formerly Account 2 — covers pre-retirement needs like housing, education, health, insurance/takaful and Hajj), and Akaun Fleksibel (10%, a new account members can withdraw from at any time, with a minimum RM50 per withdrawal, no restriction on purpose). Knowing which account a withdrawal scheme draws from tells you immediately how flexible — or restrictive — it will be.",
      "## Akaun Fleksibel: the genuinely flexible one",
      "Akaun Fleksibel is the newest and least restrictive account — members below 55 can withdraw from it at any time for any reason, subject only to a RM50 minimum per withdrawal, though EPF encourages using it for emergencies and immediate needs rather than routine spending. Applications go through the KWSP i-Akaun app, the i-Akaun web portal, or an EPF office, with payment credited directly to an active bank account registered in the member's own name.",
      "## Full withdrawal at 55 and 60",
      "At 55, your Akaun Persaraan, Akaun Sejahtera and Akaun Fleksibel balances consolidate into a single Akaun 55, which you can withdraw from (in part or in full) or leave invested to keep earning dividends. Any contributions made after turning 55 go into a separate Akaun Emas, which stays locked until age 60 — at which point it can be withdrawn in full, no conditions attached.",
      "## Housing, education, health, insurance and Hajj withdrawals",
      "Akaun Sejahtera permits withdrawals for a first home's down payment or ongoing mortgage repayment, for a child's (or your own) tertiary education fees at an approved institution, for approved medical treatment for yourself or immediate family, for insurance or takaful protection premiums, for performing Hajj, and for a one-off withdrawal at age 50. Each scheme has its own minimum balance requirement, supporting document list, and — for several of these — a cap on how much you can claim per approved item.",
      "## Leaving the workforce or the country",
      "Members who emigrate permanently and renounce Malaysian citizenship can withdraw their full EPF savings, subject to immigration and tax clearance. There are also specific (much more restrictive) withdrawal provisions for members who become permanently incapacitated or pass away, where savings are paid to nominated beneficiaries or next of kin.",
      "## Why this matters even if you're nowhere near 55",
      "Every early withdrawal permanently reduces the base your retirement dividends compound on — pulling out RM20,000 in your 30s doesn't just cost you RM20,000, it costs you every year of dividends that amount would have earned for the next two or three decades. None of this is a reason to never withdraw early; housing and education withdrawals fund things that build wealth too. It's a reason to run the actual numbers before deciding, rather than assuming the money is either fully locked or free to take.",
    ],
    relatedLinks: [
      { href: "/epf-calculator", label: "EPF Calculator (KWSP)" },
      { href: "/epf-account-split-calculator", label: "EPF Account Split Calculator" },
      { href: "/epf-retirement-calculator", label: "EPF Retirement Goal Calculator" },
    ],
  },
  {
    slug: "first-paycheck-malaysia-what-to-expect",
    title: "What Your First Paycheck in Malaysia Actually Looks Like",
    description: "You accepted a job at a certain salary. Here's why the number that hits your bank account is smaller — and exactly where each Ringgit of the difference goes.",
    publishedDate: "2026-06-02",
    body: [
      "Nothing quite prepares first-time employees for the gap between the salary figure on their offer letter and the number that actually shows up in their bank account a month later. It's not a mistake, and it's not being shortchanged — it's four separate, legally required deductions, each doing something specific.",
      "## Your offer letter number is gross, not net",
      "When a job offer says 'RM3,500 per month', that's your gross salary — the full amount before any deduction. Nobody actually takes home their full gross salary in Malaysia if they're a formal employee, because EPF, SOCSO, EIS and (above a certain income) PCB are all deducted before the money reaches you.",
      "## The four deductions, in the order they matter",
      "EPF takes the biggest bite — typically 11% of your wage — but it's the one deduction that isn't really 'lost': it's going into a retirement account that's legally yours. SOCSO and EIS together take a much smaller slice (often under 1% combined for typical entry-level wages) and fund injury and unemployment protection. PCB, the income tax component, is often zero or close to it for a first job, because the automatic tax reliefs (individual relief, EPF relief) push most starting salaries below the taxable threshold entirely.",
      "## Why your second paycheck might differ from your first",
      "If your first month included a pro-rated partial salary (you joined mid-month), your EPF/SOCSO/EIS deductions that month will be proportionally smaller too, since they're all calculated as a percentage of whatever you were actually paid. Don't panic if your first and second full paychecks don't match perfectly — check whether the first one was pro-rated before assuming something's wrong.",
      "## A number worth knowing before you negotiate your next offer",
      "Because EPF's employer contribution and SOCSO/EIS's employer share are paid on top of your salary, your actual cost to a company is meaningfully higher than your gross pay — often 13-15% more. This matters when you're negotiating: a company weighing 'can we afford this hire' is looking at that fully-loaded number, not just the salary they're offering you.",
      "## Checking your own number before day one",
      "If you already know your offered salary, marital status and whether you have dependents, you can work out almost exactly what your first full paycheck will look like before you've even started — which makes budgeting for rent, transport and the rest of adult life considerably less of a guessing game.",
    ],
    relatedLinks: [
      { href: "/", label: "Full Salary Calculator" },
      { href: "/epf-calculator", label: "EPF Calculator (KWSP)" },
      { href: "/socso-calculator", label: "SOCSO Calculator (PERKESO & EIS)" },
      { href: "/payslip-generator", label: "Payslip Generator" },
    ],
  },
  {
    slug: "real-cost-of-hiring-in-malaysia",
    title: "The Real Cost of Hiring: What Employers Pay Beyond Salary",
    description: "The salary you offer isn't what the hire actually costs you. A breakdown of the statutory contributions every Malaysian employer pays on top of gross pay.",
    publishedDate: "2026-06-25",
    body: [
      "Small business owners planning their first few hires often budget headcount cost as 'salary times number of people' — and then get a mild shock when the actual payroll run is noticeably higher. The gap isn't an accounting error; it's a set of statutory employer contributions that exist specifically to sit on top of the salary you advertise.",
      "## The three mandatory add-ons",
      "For a typical Malaysian citizen employee below 60 earning RM5,000 or less, an employer pays 13% of wages into EPF (versus the employee's 11%), roughly 1.75% into SOCSO, and 0.2% into EIS — all calculated on top of, not deducted from, the salary you're paying. Add these up and a RM3,000/month hire typically costs closer to RM3,450-3,500 once employer contributions are included, before you've spent a Ringgit on equipment, software licences or office space for them.",
      "## It scales differently depending on who you hire",
      "Employees aged 60 and above cost less in EPF (a flat 4% employer share, no employee deduction at all past that age for citizens) but the SOCSO scheme narrows to Employment Injury coverage only. Non-Malaysian employees now carry a mandatory 2% EPF employer contribution (since October 2025) plus an employer-only SOCSO Employment Injury contribution, but no EIS liability at all. None of these are exotic edge cases for a growing Malaysian business — they're the everyday mix of who actually gets hired.",
      "## The number that's easy to forget: bonuses",
      "Because EPF treats bonuses as ordinary wages, a RM5,000 bonus doesn't just cost RM5,000 — it costs that plus your EPF employer contribution on top (12-13% depending on the wage band), landing closer to RM5,600-5,650 in real cash outlay. SOCSO and EIS, by contrast, explicitly exclude bonuses from their wage calculation, so at least those two don't scale with bonus payouts.",
      "## Why this matters for pricing your own services",
      "If you run an agency, consultancy or any services business where staff cost is your main input cost, quoting client rates based on gross salary alone quietly erodes your margin every single month. Building in the employer-contribution loading — typically an extra 13-15% on top of gross salary for a standard Malaysian citizen hire — from the start avoids discovering the gap only when you look at your actual bank balance at month end.",
      "## Budgeting it properly",
      "The cleanest way to budget a new hire isn't 'salary plus a rough buffer' — it's calculating the actual EPF, SOCSO and EIS employer contributions for that specific wage, age group and nationality, since the percentages genuinely differ across those variables. It takes under a minute per hire and removes the guesswork entirely.",
    ],
    relatedLinks: [
      { href: "/epf-calculator", label: "EPF Calculator (KWSP)" },
      { href: "/socso-calculator", label: "SOCSO Calculator (PERKESO & EIS)" },
      { href: "/guides/epf-employer-contribution-guide-malaysia", label: "EPF Employer Contribution Guide" },
      { href: "/payslip-generator", label: "Payslip Generator" },
    ],
  },
  {
    slug: "epf-socso-eis-foreign-workers-2025-changes",
    title: "EPF, SOCSO and EIS for Foreign Workers: 2025 Rule Changes",
    description: "Mandatory EPF for foreign employees is new as of October 2025. Here's what actually changed, what didn't, and what employers need to update in payroll.",
    publishedDate: "2026-07-18",
    body: [
      "For years, the statutory contribution rules for foreign workers in Malaysia sat quietly apart from the rules everyone else followed: no mandatory EPF, limited SOCSO coverage, and no EIS at all. From October 2025, one of those three pillars changed materially, and it's worth being precise about exactly what did and didn't move.",
      "## What changed: EPF is now mandatory",
      "Starting with wages paid from October 2025 onward, non-Malaysian employees (holding a valid passport and employment pass, excluding domestic workers) are subject to mandatory EPF contributions at 2% from the employee and 2% from the employer — a flat rate regardless of wage level or age, unlike the tiered percentages that apply to Malaysian citizens and permanent residents. This followed a proposed rate as high as 12% during initial Budget discussions, later reduced to 2%+2% after consultation with business groups concerned about the cost impact on labour-intensive sectors.",
      "## What didn't change: SOCSO and EIS",
      "Foreign workers remain covered under SOCSO's Employment Injury Scheme on an employer-paid-only basis — there was no change here in 2025. EIS continues to apply exclusively to Malaysian citizens and permanent residents; foreign employees are still entirely outside the EIS system, with no contribution required from either side and no unemployment benefit eligibility.",
      "## Why this specific change happened now",
      "The policy rationale centres on retirement adequacy: as reliance on foreign labour has grown across manufacturing, construction, plantation and services sectors, foreign workers were accumulating no formal retirement savings from their Malaysian employment at all. A modest, capped contribution rate was framed as extending baseline financial protection without imposing the same cost structure that applies to citizen employees.",
      "## What employers actually need to update",
      "Payroll systems needed to add a new EPF contributor category (2% flat, any wage, any age) that didn't previously exist for this group, and HR teams needed to re-issue any employment cost projections that assumed foreign hires carried no EPF liability. For a business with a significant foreign workforce, this is a real, recurring cost increase — not a one-off compliance box to tick.",
      "## What to watch for next",
      "Rate changes affecting foreign worker contributions have moved faster and been debated more publicly than most other statutory adjustments in recent years, which makes this a category worth rechecking before every Budget rather than assuming it's settled. Our rate changes page tracks the current and previous rates we've verified, specifically so you don't have to re-research this from scratch each time.",
    ],
    relatedLinks: [
      { href: "/epf-calculator", label: "EPF Calculator (KWSP)" },
      { href: "/socso-calculator", label: "SOCSO Calculator (PERKESO & EIS)" },
      { href: "/rate-changes", label: "Rate Change History" },
    ],
  },
  {
    slug: "malaysia-income-tax-rate-brackets-explained",
    title: "Malaysia Income Tax Rate 2026: Brackets, Rebates & Deadline",
    description: "Malaysia's tax rate is progressive, not flat — here's exactly how the brackets work, what the RM400 rebate actually requires, and when your return is due.",
    publishedDate: "2026-08-05",
    body: [
      "A lot of confusion about Malaysian income tax comes from one mix-up: people hear their 'tax rate' is 19% or 25% and assume that's what's deducted from their entire income. It isn't. Malaysia uses a progressive bracket system — you're taxed at each bracket's rate only for the slice of income that falls inside it, not your whole chargeable income at the top rate you reach.",
      "## How the brackets actually work",
      "The first RM5,000 of chargeable income is taxed at 0%. Above that, rates step up gradually — 1% on the next portion, then 3%, 6%, 11%, 19%, 25%, 26%, 28%, and 30% at the very top bracket for chargeable income above RM2,000,000. 'Chargeable income' here is the key term: it's your total income after all reliefs and deductions are subtracted, not your gross salary. Two people earning the same gross salary can land in different effective tax positions purely based on the reliefs they claim.",
      "## Why your effective rate is always lower than your top bracket",
      "If your chargeable income pushes you into the 19% bracket, that doesn't mean 19% of your income goes to tax — only the portion inside that specific bracket does. Everything below it was still taxed at the lower rates that applied to those slices. This is why a rough mental calculation ('I'm in the 19% bracket, so I owe 19% of my income') always overstates the real bill. Running your actual numbers through a bracket-aware calculator is the only reliable way to see your true effective rate.",
      "## The RM400 rebate most people miss",
      "If your chargeable income is RM35,000 or less, you're entitled to a RM400 tax rebate — not a relief that reduces your chargeable income, but a direct cut to the tax amount you'd otherwise owe. For chargeable income right around that threshold, this rebate can be the difference between owing a noticeable sum and owing almost nothing. It's applied automatically during assessment, but it's worth knowing it exists so a small bill doesn't come as a surprise.",
      "## Resident vs non-resident rates are a completely different system",
      "Everything above applies to Malaysian tax residents — broadly, anyone who spends 182 days or more in Malaysia in a calendar year. Non-residents are taxed at a flat rate on Malaysian-sourced income, with none of the progressive brackets, individual relief, or rebate available to residents. This flat rate is meaningfully higher than what most residents pay on comparable income, which is why tax residency status (not nationality) is the detail that actually decides which system applies to you.",
      "## When your return is actually due",
      "For individuals with employment income only (no business income), e-Filing typically closes by 30 April of the following year, with LHDN sometimes granting a short grace period for online submissions specifically. Filers who also report business income usually get until 30 June. These dates are set by LHDN each year rather than fixed permanently in law, so always confirm the current year's exact deadline on the MyTax portal rather than assuming last year's date carries over unchanged.",
      "## Where PCB fits into all this",
      "The PCB deducted from your monthly paycheck is meant to be a running estimate of this exact bracket calculation, spread across the year so you're not hit with the full annual bill at filing time. When PCB is calculated correctly against your actual reliefs, your annual filing should show only a small top-up or refund — a large one in either direction usually means your declared reliefs changed mid-year, or your employer's payroll system is using outdated figures.",
    ],
    relatedLinks: [
      { href: "/income-tax-calculator", label: "Income Tax Calculator" },
      { href: "/pcb-calculator", label: "PCB Calculator (MTD)" },
      { href: "/", label: "Full Salary Calculator" },
    ],
  },
  {
    slug: "epf-employer-contribution-guide-malaysia",
    title: "EPF Employer Contribution: Rates, Deadlines and Registration",
    description: "Registering, calculating and paying EPF as an employer — the rates, the 15th-of-the-month deadline, and what happens if you miss it.",
    publishedDate: "2026-09-21",
    body: [
      "Most guides to EPF are written for employees checking their own payslip. This one is for the other side of that transaction — what a Malaysian employer is actually required to do, by when, and what happens if it slips.",
      "## Registering as an EPF employer",
      "Under Section 41(1) of the EPF Act 1991, an employer must register with EPF within 7 days of becoming liable to contribute — in practice, as soon as you hire your first employee. Registration is done by submitting KWSP Form 1 along with your company's registration documents. This applies to every SSM-registered business the moment it takes on staff, not just larger companies; there's no employee-count threshold that exempts a small business from registering.",
      "## What you actually owe, by category",
      "For a Malaysian citizen or PR employee below 60 earning RM5,000 or less a month, the employer share is 13% of wages (12% above RM5,000) — compared to the employee's flat 11%. For employees aged 60 and above, the employer share drops to a flat 4%, with no employee deduction at all past that age. Non-Malaysian employees carry a mandatory employer contribution of 2%, flat regardless of wage or age, since this became mandatory in October 2025. All of these are calculated on top of the wage you pay, not deducted from it.",
      "## The payment deadline: the 15th of the following month",
      "EPF contributions for a given month's wages must be paid by the 15th of the following month. If the 15th falls on a weekend or public holiday, payment made on the next working day is still accepted. This deadline applies to both the employer and employee shares — as the employer, you're responsible for remitting both together, even though only the employer's portion is your own money.",
      "## What happens if you're late",
      "Missing the 15th triggers a Late Payment Charge, calculated as the equivalent of the prevailing EPF dividend rate plus an additional 1%, applied to the overdue amount. This isn't a token penalty — EPF has published late-payment charge collections in the tens of millions of Ringgit in past annual reports, so it's actively enforced, not a formality. Beyond the financial charge, the EPF Act treats failure to pay contributions as a criminal offence, and EPF has publicly reported enforcement actions including barring company directors from leaving the country over unpaid contributions — this is treated as a genuine compliance obligation, not a soft administrative requirement.",
      "## A common mistake: forgetting bonuses and irregular payments",
      "EPF treats bonuses, commissions and most allowances as wages for contribution purposes, so a bonus run needs the same employer contribution applied as a regular payroll run — it's easy to forget this on an irregular, once-a-year payment and under-remit without realising it. Recalculating contributions for every payment type, not just base salary, is the safest way to avoid an unplanned shortfall showing up at your next EPF audit.",
      "## Keeping this simple in practice",
      "The actual math — employer share by category, total monthly liability across a mixed team of citizens, PR holders, seniors and foreign employees — is where most of the manual error creeps in, not the registration or payment process itself. Running each employee's wage through a calculator that already applies the correct category rate removes that risk, and is worth doing every time your headcount or wage bands change rather than relying on a rate you memorised once.",
    ],
    relatedLinks: [
      { href: "/epf-calculator", label: "EPF Calculator (KWSP)" },
      { href: "/epf-account-split-calculator", label: "EPF Account Split Calculator" },
      { href: "/guides/real-cost-of-hiring-in-malaysia", label: "The Real Cost of Hiring in Malaysia" },
    ],
  },
  {
    slug: "lindung-24-jam-socso-new-scheme-2026",
    title: "LINDUNG 24 Jam Explained: PERKESO's New Accident Scheme",
    description: "A new SOCSO scheme launched 1 June 2026 covers accidents outside work too — here's the phased rate, who it's mandatory for, and who can opt in.",
    publishedDate: "2026-09-23",
    body: [
      "Most people know SOCSO as protection for accidents that happen at work. Since 1 June 2026, there's a genuinely new scheme that extends coverage well beyond that — and because it's this new, a lot of employees and even some employers haven't caught up on what it actually means for their payslip.",
      "## What LINDUNG 24 Jam actually covers",
      "LINDUNG 24 Jam — officially Skim Kemalangan Bukan Bencana Kerja (SKBBK), the Non-Employment Injury Scheme — covers accidents that happen outside work and aren't related to your job at all: a road accident on your day off, a fall at home, anything that counts as an accident but isn't a workplace injury (which is already covered separately under the existing Employment Injury Scheme) and isn't an illness. Coverage runs 24 hours a day, every day, for as long as you're an enrolled, employed member — including past age 60, which is different from how standard SOCSO categories change at that age.",
      "## The rate is phased, and it's paid entirely by the employee",
      "Unlike SOCSO and EIS, which split contributions between employer and employee, LINDUNG 24 Jam is funded entirely by the employee — the employer's share is RM0. The employee rate is phased in over time: 0.75% of wages for the first two years from launch, rising to 1.0% for the next three years, then 1.25% from year six onward. It uses the same RM6,000 monthly wage ceiling as SOCSO and EIS, so the current Phase 1 contribution tops out at RM45 a month (0.75% of RM6,000) even for higher earners.",
      "## Voluntary for citizens and PRs, mandatory for foreign workers",
      "This is the detail that trips people up: for Malaysian citizens and permanent residents, LINDUNG 24 Jam is opt-in — you choose whether to participate, and nothing is deducted unless you do. For non-Malaysian employees, it's mandatory under current rules, deducted automatically like SOCSO's Employment Injury coverage already is for that group. If you're a foreign worker, this isn't something you can decline; if you're a citizen or PR, it genuinely is your call.",
      "## What isn't covered",
      "PERKESO explicitly excludes a handful of cases: accidents that happen outside Malaysia, actual workplace injuries (those stay under the existing Employment Injury Scheme), domestic disasters under separate legislation, and anything caused by illness — a diabetic episode or a fever isn't an 'accident' under this scheme's definition, even if it leads to a fall or injury. It's specifically for genuine accidents, not health conditions.",
      "## Should you opt in, if you're eligible to choose?",
      "That's a personal decision based on your existing coverage — if you already have personal accident insurance or your employer provides group coverage for non-work accidents, LINDUNG 24 Jam may be redundant. If you have no other accident coverage outside work, RM45 a month (or less, depending on your wage) for genuine 24-hour accident protection is a modest cost relative to the protection. Either way, it's worth actually deciding rather than defaulting into whatever your employer's payroll system happens to be set to.",
    ],
    relatedLinks: [
      { href: "/socso-calculator", label: "SOCSO Calculator (PERKESO & EIS)" },
      { href: "/", label: "Full Salary Calculator" },
    ],
  },
  {
    slug: "budget-2027-malaysia-salary-epf-socso",
    title: "Budget 2027 Malaysia: What It Could Mean for Your Salary",
    description:
      "Malaysia tables Budget 2027 on 9 October 2026. What the official Pre-Budget Statement says about EPF and SOCSO, and what is still unconfirmed.",
    publishedDate: "2026-09-24",
    body: [
      "The Malaysian government will table Budget 2027 in Parliament on 9 October 2026 — the fifth Budget under the MADANI administration. Budgets regularly touch the numbers this site calculates: PCB tax brackets and reliefs, sometimes EPF or SOCSO rates. Here's what's actually been said officially so far, and what hasn't.",
      "## What the government has confirmed it's reviewing",
      "The Ministry of Finance's Pre-Budget Statement, published 18 August 2026, explicitly names social protection as one of Budget 2027's ten focus areas. Its own wording: the government will \"reassess the adequacy and sustainability of Malaysia's social protection system, including coverage under the EPF, Social Security Organisation (SOCSO) and related schemes,\" with stated priority on \"extending protection to informal workers, gig workers and vulnerable groups.\" That's a direct, on-the-record signal that EPF and SOCSO coverage rules are under active review — not a rumour.",
      "## What that does not tell you",
      "A pre-budget statement sets discussion priorities; it doesn't fix numbers. Nothing in the official statement commits to a specific contribution rate, wage ceiling, or bracket change for EPF, SOCSO, EIS or PCB. Treat any specific percentage you see quoted online before 9 October as speculation, regardless of how confidently it's written — that includes speculation from us. We won't publish a number here until it's been announced.",
      "## The pattern from past MADANI budgets",
      "For context on how directly a budget can move these figures: the first MADANI Budget cut the resident personal income-tax rate by 2 percentage points for every income band from RM35,001 to RM100,000, worth up to RM1,300 a year to about 2.4 million taxpayers. The SOCSO/EIS wage ceiling rose from RM5,000 to RM6,000 in October 2024, and mandatory EPF for non-Malaysian employees began in October 2025. Budgets here have a real track record of changing take-home pay, not just headline policy.",
      "## What we'll do when it's tabled",
      "We check LHDN, KWSP and PERKESO directly against the actual Budget 2027 announcement on 9 October, and update every calculator on this site — PCB, EPF, SOCSO, EIS — the same day if anything statutory actually changes, sourced and verifiable, not copied from a headline. If nothing changes for a given rate, we leave it alone rather than manufacturing a reason to post about it.",
    ],
    relatedLinks: [
      { href: "/pcb-calculator", label: "PCB Calculator (MTD)" },
      { href: "/epf-calculator", label: "EPF Calculator (KWSP)" },
      { href: "/socso-calculator", label: "SOCSO Calculator (PERKESO & EIS)" },
      { href: "/rate-changes", label: "Rate Change History" },
    ],
  },
  {
    slug: "is-your-salary-good-in-malaysia",
    title: "Is Your Salary Good in Malaysia? What the Data Says",
    description:
      "Is RM7,000 or RM25,000 a good salary in Malaysia? Real DOSM wage data — not opinion — to actually benchmark your pay against.",
    publishedDate: "2026-09-24",
    body: [
      "\"Is my salary good?\" is one of the most searched questions about pay in Malaysia, and almost every answer online is a guess dressed up as advice. There's an actual, official answer: the Department of Statistics Malaysia (DOSM) publishes real wage data every quarter. Here's what it actually says, as of the latest release.",
      "## The real national benchmark",
      "DOSM's Employee Wages Statistics (Formal Sector) report for Q4 2025, released 29 April 2026, puts the median monthly wage for Malaysian formal-sector employees at RM3,167 (December 2025) — up 4.0% from RM3,045 a year earlier. Percentile data from the same release shows the bottom 10% of formal employees earned RM1,700 or less, while the top 10% (the 90th percentile) earned at least RM11,122 a month.",
      "## So is RM7,000 a good salary?",
      "RM7,000 sits well above the national median of RM3,167 — more than double it — though it's still short of the RM11,122 threshold that marks the top 10% of earners. In plain terms: comfortably above average, not yet in the very top bracket.",
      "## And RM25,000?",
      "RM25,000 is more than double the RM11,122 threshold for the top 10% of Malaysian formal employees. That places it firmly in the highest-earning bracket nationally, by DOSM's own numbers — not a subjective call.",
      "## Where you live changes the answer",
      "The same salary buys very different things depending on where you are. DOSM's December 2025 figures show Kuala Lumpur's median wage at RM4,391, Penang at RM3,500 and Selangor at RM3,400 — all well above Kelantan's RM1,800, Perlis's RM1,864 and Sabah's RM2,045. A salary that looks average in KL would be well above the local median in several other states, and vice versa — the honest comparison is against your own state, not the national figure alone.",
      "## Age and experience change it too",
      "DOSM also breaks median wages down by age band. Employees aged 45–49 recorded the highest median in Q4 2025 (reaching RM4,245 in December), while employees under 20 had a median of RM1,700. Comparing your salary against your own age group's median is usually more useful than the all-ages national figure, especially early or late in a career.",
      "## The number that actually matters more: take-home pay",
      "Two people on the same gross salary can end up with meaningfully different take-home pay, depending on age, marital status, number of children and EPF/SOCSO category. Gross salary benchmarks are a starting point, not the full picture — what actually lands in your bank account after EPF, SOCSO, EIS and PCB is the number worth comparing.",
    ],
    relatedLinks: [
      { href: "/", label: "Full Salary Calculator" },
      { href: "/pcb-calculator", label: "PCB Calculator (MTD)" },
      { href: "/guides/first-paycheck-malaysia-what-to-expect", label: "What Your First Paycheck Actually Looks Like" },
    ],
  },
  {
    slug: "salary-calculation-30-or-31-days-malaysia",
    title: "Is Salary Calculated on 30 or 31 Days in Malaysia?",
    description:
      "The Employment Act's real formula for partial-month salary uses the actual days in that month, not a fixed 30 — here's how it actually works.",
    publishedDate: "2026-09-24",
    body: [
      "Your monthly salary is a fixed number, so it's a fair question: when you only work part of a month — you start mid-month, resign before month-end, or take a stretch of unpaid leave — is that partial pay worked out on 30 days, 31 days, or something else? The answer is more specific than most explanations online suggest.",
      "## The legal default: the actual number of days in that month",
      "Under the Employment Act 1955 (Section 18A, read together with Section 60I(2)), the statutory formula for an incomplete month of work is: monthly wage ÷ the number of days in that particular wage period, × the number of days the employee actually worked or was entitled to be paid for. \"The number of days in that particular wage period\" means the real calendar length of that specific month — 28 or 29 in February, 30 in April, June, September and November, and 31 in the rest. It is not a fixed divisor.",
      "## Why you'll still see companies use a flat 26 or 30",
      "Employers are allowed to use a different, simpler method — a fixed divisor of 26 or 30, for example — but only if the result is equal to or more generous than what the calendar-day formula would give the employee. A flat divisor that would pay the employee less than the statutory formula isn't compliant, even if it's what's written in the employment contract. So both approaches exist in practice, and the one that matters legally is whichever produces the larger number for the employee.",
      "## A worked example",
      "Say your monthly salary is RM5,000 and you start a new job on 16 February 2026 — a month with 28 days. Under the statutory formula, you'd be paid for 13 days out of 28: RM5,000 ÷ 28 × 13 = RM2,321.43. If your employer instead used a fixed 30-day divisor, you'd get RM5,000 ÷ 30 × 13 = RM2,166.67 — less than the statutory result, which would not be compliant. A fixed divisor only becomes legal here if it's adjusted so the outcome is at least as favourable as the calendar-day method.",
      "## When this actually comes up",
      "This only affects partial months — starting or leaving mid-month, or unpaid leave spanning part of a pay period. A full calendar month worked in full is paid at your full monthly salary regardless of whether that month has 28, 30 or 31 days; the divisor only changes the answer when you're being paid for less than the whole period.",
    ],
    relatedLinks: [
      { href: "/hourly-rate-calculator", label: "Hourly & Daily Rate Calculator" },
      { href: "/guides/first-paycheck-malaysia-what-to-expect", label: "What Your First Paycheck Actually Looks Like" },
      { href: "/", label: "Full Salary Calculator" },
    ],
  },
  {
    slug: "epf-dividend-2026-what-we-know",
    title: "EPF Dividend 2026: What We Know So Far",
    description:
      "Searching for the EPF 2026 dividend rate? Here is exactly what KWSP has confirmed, the real announcement date pattern, and what is still unknown.",
    publishedDate: "2026-09-27",
    body: [
      "If you've searched for \"EPF dividend 2026,\" here's the direct answer: it hasn't been announced yet, and won't be for several more months. That's not a non-answer — knowing exactly when it's coming, and what's already confirmed in the meantime, is genuinely useful.",
      "## The pattern: dividends are announced the following February",
      "EPF declares each calendar year's dividend the following year, typically in the last week of February, with the amount credited to members' accounts on or around 1 March. The 2025 dividend — 6.15% for both Simpanan Konvensional and Simpanan Shariah — was announced on 28 February 2026 and credited 1 March 2026, with a total payout of RM79.6 billion. Following that same pattern, the 2026 dividend won't be announced until roughly late February 2027.",
      "## What's actually confirmed right now",
      "The most recent declared rate is the 2025 dividend: 6.15% for Simpanan Konvensional, 6.15% for Simpanan Shariah. That's the rate currently being credited and the most relevant figure for any planning you're doing today — it is not the 2026 rate, which doesn't exist yet.",
      "## Why the confusion happens",
      "Two things get mixed up every year: people search \"EPF dividend [current year]\" expecting a rate that's actually announced the following year, and some sites publish \"forecast\" or \"expected\" figures for the still-unannounced year that read like confirmed numbers. Treat any specific 2026 percentage you see quoted before late February 2027 as speculation, not fact — including anything published here before that date.",
      "## What determines the rate, and why it's never guaranteed",
      "EPF's dividend is not a fixed interest rate — it's declared annually based on the fund's actual investment performance that year, split (since 2017) into a conventional and a Shariah-compliant rate. By law, the minimum guaranteed rate is 2.50% a year for Simpanan Konvensional; every year's actual declared rate has been at or above that floor, but nothing above the legal minimum is promised in advance.",
      "## The historical range, for context",
      "Over the last decade, the conventional rate has moved between 5.20% (2020, the pandemic year) and 6.90% (2017), averaging in the mid-to-high 5% to low 6% range most years. That's a reasonable planning band — not a prediction — until the actual 2026 rate is declared.",
    ],
    relatedLinks: [
      { href: "/epf-retirement-calculator", label: "EPF Retirement & Dividend Calculator" },
      { href: "/epf-calculator", label: "EPF Calculator (KWSP)" },
      { href: "/guides/epf-dividend-2025-rate-history", label: "EPF Dividend 2025: Rate & History" },
      { href: "/rate-changes", label: "Rate Change History" },
    ],
  },
  {
    slug: "epf-dividend-2025-rate-history",
    title: "EPF Dividend 2025: 6.15% Rate, History & How It's Paid",
    description:
      "KWSP declared a 6.15% dividend for 2025 (Konvensional and Shariah), credited 1 March 2026. See past years' rates and how to check your dividend.",
    publishedDate: "2026-10-06",
    body: [
      "KWSP declared a dividend of 6.15% for both Simpanan Konvensional and Simpanan Shariah for 2025. It was announced on 28 February 2026 and credited to members' accounts on 1 March 2026, with a total payout of RM79.6 billion. That is the confirmed figure — earlier forecasts of 6.3% to 6.5% were expectations, not the declared rate.",
      "## EPF dividend rate history",
      "The table below shows the declared rate for the last five years. Each year's dividend is announced the following February.",
      "## How to calculate your EPF dividend",
      "A simple estimate is your balance multiplied by the declared rate. For example, RM50,000 held for the whole year at 6.15% would earn about RM3,075. Your actual dividend can differ, because it depends on when contributions went in and on any withdrawals during the year, so treat this as a guide rather than an exact figure. To see how dividends compound over many years, use the EPF retirement calculator.",
      "## When was the 2025 dividend credited, and how do I check it?",
      "The 2025 dividend was credited on 1 March 2026. You can check your dividend statement through i-Akaun (website or app), which showed statements from 28 February 2026, or at a KWSP self-service terminal. The dividend is credited to each of your accounts based on that account's balance.",
      "## Konvensional or Shariah: does it matter?",
      "For 2025 and 2024 both savings types received the same rate. In earlier years they differed — in 2022, for example, the conventional rate was 5.35% against 4.75% for Shariah — so it is worth knowing which type your savings are in. You can see this in i-Akaun.",
      "## What about the 2026 dividend?",
      "The 2026 dividend has not been declared. Following the usual pattern, expect the announcement in the last week of February 2027. Any specific 2026 percentage quoted before then is speculation.",
    ],
    table: {
      afterIndex: 2,
      caption: "EPF dividend rates by year",
      headers: ["Year", "Simpanan Konvensional", "Simpanan Shariah"],
      rows: [
        ["2025", "6.15%", "6.15%"],
        ["2024", "6.30%", "6.30%"],
        ["2023", "5.50%", "5.40%"],
        ["2022", "5.35%", "4.75%"],
        ["2021", "6.10%", "5.65%"],
      ],
    },
    faq: [
      {
        q: "What is the EPF dividend for 2025?",
        a: "6.15% for both Simpanan Konvensional and Simpanan Shariah. KWSP announced it on 28 February 2026 and credited it to members' accounts on 1 March 2026, with a total payout of RM79.6 billion.",
      },
      {
        q: "When will the EPF 2026 dividend be announced?",
        a: "It has not been declared yet. KWSP usually announces the previous year's dividend in the last week of February, so the 2026 dividend is expected around late February 2027.",
      },
      {
        q: "How do I check my EPF dividend?",
        a: "Log in to i-Akaun (website or app) and open your statement, or use a KWSP self-service terminal. The dividend is credited to each of your accounts based on that account's balance.",
      },
    ],
    relatedLinks: [
      { href: "/epf-retirement-calculator", label: "EPF Retirement & Dividend Calculator" },
      { href: "/epf-calculator", label: "EPF Calculator (KWSP)" },
      { href: "/guides/epf-dividend-2026-what-we-know", label: "EPF Dividend 2026: What We Know" },
    ],
  },
  {
    slug: "tax-relief-2026-malaysia-ya-2025",
    title: "Tax Relief 2026 Malaysia (YA 2025): Full List & Amounts",
    description:
      "Every LHDN personal tax relief for YA 2025 (filed in 2026) with exact amounts: individual, EPF, lifestyle, medical, children, parents and more.",
    publishedDate: "2026-10-06",
    body: [
      "\"Tax relief 2026\" usually means the reliefs you claim when you file in 2026. That is Year of Assessment (YA) 2025, covering income you earned in 2025. A relief reduces your chargeable income, so your tax is calculated on a smaller amount. The table below lists the main LHDN personal reliefs for YA 2025 with their limits.",
      "## Personal tax relief list (YA 2025)",
      "Each amount is the most you can claim. For most reliefs you need receipts and can only claim what you actually paid, up to the cap, and some items have smaller sub-limits inside the overall cap.",
      "## What changed for YA 2025",
      "Following Budget 2025, the relief for a disabled individual rose from RM6,000 to RM7,000 and the relief for a disabled spouse rose from RM5,000 to RM6,000. The relief for an unmarried disabled child rose from RM6,000 to RM8,000.",
      "## Tax relief versus tax rebate",
      "A relief lowers your chargeable income before tax is calculated. A rebate lowers the tax itself: if your chargeable income is RM35,000 or less you get a RM400 tax rebate, applied after your tax is worked out.",
      "## See what your reliefs do to your tax",
      "Enter your income and reliefs in our income tax calculator to see your chargeable income, tax by band and tax payable. It applies the individual, EPF, SOCSO/EIS, spouse, child, lifestyle, medical, parent-medical and SSPN reliefs automatically. A few reliefs, such as education fees, childcare fees, PRS, EV charging and breastfeeding equipment, are not in the calculator yet, so your actual tax may be lower than the estimate.",
      "## Check the official list before you file",
      "This page is a summary. Relief amounts and conditions can change with each Budget, so confirm them against LHDN's official relief schedule at hasil.gov.my before you file.",
    ],
    table: {
      afterIndex: 2,
      caption: "Personal tax reliefs, YA 2025",
      headers: ["Relief", "Maximum (RM)", "Notes"],
      rows: [
        ["Individual", "9,000", "Automatic, no receipts"],
        ["Disabled individual", "7,000", "Up from 6,000; JKM certification"],
        ["Spouse or alimony", "4,000", "Spouse with no income"],
        ["Disabled spouse", "6,000", "Up from 5,000"],
        ["Child under 18", "2,000 each", "Unmarried"],
        ["Child 18+ in full-time education", "2,000 each", "A-level, certificate, matriculation"],
        ["Child 18+ in diploma or higher", "8,000 each", "Higher education"],
        ["Disabled child", "8,000", "Up from 6,000"],
        ["EPF contributions", "4,000", "Your own contributions"],
        ["Life insurance or takaful", "3,000", "Premiums paid"],
        ["SOCSO and EIS", "350", "Your own contributions"],
        ["Lifestyle", "2,500", "Books, devices, internet, skills courses"],
        ["Sports equipment and gym", "1,000", "Separate from lifestyle"],
        ["Medical expenses", "10,000", "Serious diseases, fertility, dental, vaccination, mental health; some sub-limits"],
        ["Medical care for parents", "8,000", "Treatment, special needs or carer"],
        ["Education fees (self)", "7,000", "Upskilling courses up to 2,000"],
        ["SSPN net deposit", "8,000", "Net savings in the year"],
        ["PRS", "3,000", "Private Retirement Scheme"],
        ["Childcare or kindergarten fees", "3,000", "Child aged 6 and under"],
        ["Breastfeeding equipment", "1,000", "Once every 2 years"],
        ["EV charging facilities", "2,500", "Extended to YA 2027"],
      ],
    },
    faq: [
      {
        q: "How much is the individual tax relief in Malaysia?",
        a: "RM9,000 for YA 2025. It is automatic, so you do not need receipts to claim it.",
      },
      {
        q: "What is the difference between tax relief and tax rebate?",
        a: "A relief reduces your chargeable income before tax is calculated. A rebate reduces the tax itself. If your chargeable income is RM35,000 or less, you get a RM400 rebate.",
      },
      {
        q: "Which year does \"tax relief 2026\" refer to?",
        a: "Claims you make when you file in 2026 are for Year of Assessment 2025, which covers income earned in 2025. Reliefs for income earned in 2026 are claimed when you file in 2027.",
      },
    ],
    relatedLinks: [
      { href: "/income-tax-calculator", label: "Income Tax Calculator" },
      { href: "/pcb-calculator", label: "PCB Calculator (MTD)" },
      { href: "/guides/annual-tax-relief-checklist", label: "Annual Tax Relief Checklist" },
    ],
  },
  {
    slug: "resignation-notice-period-malaysia",
    title: "Resignation Notice Period Malaysia: How Long & Final Pay",
    description:
      "How much notice must you give to resign in Malaysia? Employment Act minimums (4, 6 or 8 weeks), how final pay is worked out, and what to put in your letter.",
    publishedDate: "2026-10-06",
    body: [
      "In Malaysia, the notice you must give when you resign is set by your employment contract. If the contract does not say, the Employment Act 1955 sets a minimum notice period that depends on how long you have worked for the employer.",
      "## Minimum notice under the Employment Act",
      "The table below shows the minimum notice where the contract is silent. The same notice applies to both the employee and the employer, and it must be given in writing.",
      "## Which notice period applies to you?",
      "Your contract comes first. If it states a notice period, which is commonly one to three months, follow that one. Notice is counted from the day you give it, and the day you give notice is included in the period. If you leave with less notice than required, you may have to pay wages in lieu for the shortfall, so check your contract.",
      "## What to include in a resignation letter",
      "Keep it short and dated: your name and position, a clear statement that you are resigning, the date you are giving notice, your last working day, and your signature. Keep a copy and ask HR to acknowledge receipt in writing.",
      "## Final salary when you leave mid-month",
      "Your last month's pay is normally pro-rated for the days you worked. Under the Employment Act method, the monthly salary is divided by the actual number of calendar days in that month and multiplied by the days worked. For example, with a salary of RM4,000 and a last day of 15 September (a 30-day month), the pay is RM4,000 ÷ 30 × 15 = RM2,000. Use the prorated salary calculator to work out your own figure.",
      "## Unused leave and other final pay",
      "Whether unused annual leave is paid out when you resign depends mainly on your contract and company policy. Ask HR for a written breakdown of your final pay so you can check each item.",
      "## If your employer ends your job",
      "When the employer ends the contract, the same minimum notice applies. If the job ends because of redundancy, separate termination benefits may apply under the Employment (Termination and Lay-Off Benefits) Regulations 1980.",
    ],
    table: {
      afterIndex: 2,
      caption: "Minimum notice if the contract is silent (Employment Act 1955, section 12)",
      headers: ["Length of service", "Minimum notice"],
      rows: [
        ["Less than 2 years", "4 weeks"],
        ["2 years to less than 5 years", "6 weeks"],
        ["5 years or more", "8 weeks"],
      ],
    },
    faq: [
      {
        q: "How much notice do I need to give to resign in Malaysia?",
        a: "Whatever your employment contract says. If the contract is silent, the Employment Act sets a minimum of 4 weeks for under 2 years of service, 6 weeks for 2 to under 5 years, and 8 weeks for 5 years or more.",
      },
      {
        q: "Is the notice period the same for the employer and the employee?",
        a: "Yes. The same length of notice applies to both sides, and the notice must be in writing.",
      },
      {
        q: "How is my last month's salary calculated if I resign mid-month?",
        a: "It is pro-rated: monthly salary divided by the actual number of calendar days in the month, multiplied by the days you worked. Our prorated salary calculator does this for you.",
      },
    ],
    relatedLinks: [
      { href: "/prorated-salary-calculator", label: "Prorated Salary Calculator" },
      { href: "/annual-leave-calculator", label: "Annual Leave Calculator" },
      { href: "/guides/salary-calculation-30-or-31-days-malaysia", label: "Salary Calculation: 30 or 31 Days?" },
    ],
  },
  {
    slug: "what-is-perkeso-socso-same",
    title: "What Is PERKESO? Is It the Same as SOCSO?",
    description:
      "PERKESO and SOCSO are the same organisation. See what it covers, how EIS fits in, and how much employees and employers contribute.",
    publishedDate: "2026-10-06",
    body: [
      "Yes, PERKESO and SOCSO are the same organisation. PERKESO stands for Pertubuhan Keselamatan Sosial, the Malay name, and SOCSO stands for Social Security Organisation, the English name. Payslips, employers and government forms use the two names interchangeably.",
      "## What PERKESO administers",
      "PERKESO runs Malaysia's social security protection for employees under three laws, summarised in the table below.",
      "## What is EIS?",
      "EIS, or Sistem Insurans Pekerjaan (SIP), is the Employment Insurance System. It is the part of PERKESO that supports employees who lose their jobs, and it is paid for by separate contributions from both employee and employer. It is not the same as the SOCSO contribution, but both appear on your payslip.",
      "## How much do you and your employer contribute?",
      "SOCSO and EIS contributions are calculated on monthly wages up to a RM6,000 ceiling. For an employee under 60 earning RM5,000 a month, the employee pays RM25.00 SOCSO and RM10.00 EIS, and the employer pays RM87.50 SOCSO and RM10.00 EIS. Wages above RM6,000 do not raise the contribution.",
      "## Calculate your own contribution",
      "Use the SOCSO calculator to see the exact PERKESO and EIS amounts for your wage, including the contribution table by salary.",
    ],
    table: {
      afterIndex: 2,
      caption: "What PERKESO (SOCSO) administers",
      headers: ["Scheme", "Law", "What it covers"],
      rows: [
        ["Employment Injury Scheme", "Employees' Social Security Act 1969 (Act 4)", "Accidents at work"],
        ["Invalidity Scheme", "Employees' Social Security Act 1969 (Act 4)", "Invalidity or death not related to work"],
        ["Self-Employment scheme", "Self-Employment Social Security Act 2017 (Act 789)", "Self-employed workers"],
        ["Employment Insurance System (EIS)", "Employment Insurance System Act 2017 (Act 800)", "Support after losing a job"],
      ],
    },
    faq: [
      {
        q: "Are PERKESO and SOCSO the same?",
        a: "Yes. PERKESO is the Malay name (Pertubuhan Keselamatan Sosial) and SOCSO is the English name (Social Security Organisation) of the same organisation.",
      },
      {
        q: "What does PERKESO mean?",
        a: "PERKESO stands for Pertubuhan Keselamatan Sosial, which is Malay for Social Security Organisation.",
      },
      {
        q: "Is EIS part of PERKESO?",
        a: "Yes. The Employment Insurance System (EIS, or SIP in Malay) is run by PERKESO under the Employment Insurance System Act 2017 and covers employees who lose their jobs.",
      },
    ],
    relatedLinks: [
      { href: "/socso-calculator", label: "SOCSO Calculator (PERKESO & EIS)" },
      { href: "/guides/lindung-24-jam-socso-new-scheme-2026", label: "LINDUNG 24 Jam Explained" },
      { href: "/", label: "Full Salary Calculator" },
    ],
  },
  {
    slug: "income-tax-malaysia-what-salary-is-taxable",
    title: "Income Tax in Malaysia: What Salary Is Taxable? (YA 2025)",
    description:
      "At what salary do you start paying income tax in Malaysia? See the annual tax at each monthly salary for a single employee, worked out from LHDN rates.",
    publishedDate: "2026-10-06",
    body: [
      "Income tax in Malaysia is not charged on your gross salary. It is charged on your chargeable income, which is your yearly income minus tax reliefs, and the rate rises in bands from 0% to 30%. A lower salary can therefore mean no tax at all.",
      "## Tax by monthly salary (single employee, YA 2025)",
      "The table shows the annual income tax for a single Malaysian employee with no children, using only the individual relief and the EPF and SOCSO/EIS reliefs, after the RM400 rebate. Married employees and those with children pay less because they have more reliefs.",
      "## Why a higher salary does not tax all your income at the top rate",
      "Each rate applies only to the slice of chargeable income inside its band. For example, the first RM5,000 is taxed at 0% and the next RM15,000 at 1%, so earning more only raises the tax on the extra slice, not on everything.",
      "## PCB is not the same as your final tax",
      "The PCB (monthly tax deduction) taken from your pay is an instalment. Your final income tax is worked out when you file your return, and any PCB paid above that amount is refunded.",
      "## Check your own figure",
      "Enter your annual income and reliefs in the income tax calculator for your exact tax, or use the PCB calculator for the monthly deduction.",
    ],
    table: {
      afterIndex: 2,
      caption: "Annual income tax by monthly salary",
      headers: ["Monthly salary", "Chargeable income", "Annual tax", "Average per month"],
      rows: taxBySalaryRows(),
    },
    faq: [
      {
        q: "At what salary do you start paying income tax in Malaysia?",
        a: "It depends on your reliefs. In the table above, a single employee with no children and only the standard reliefs pays RM0 tax at RM3,000 a month and starts paying a small amount at about RM3,500. Married employees and those with children start paying at a higher salary.",
      },
      {
        q: "Is income tax charged on gross salary?",
        a: "No. It is charged on chargeable income, which is your income minus tax reliefs such as the RM9,000 individual relief and your EPF contributions.",
      },
      {
        q: "Does a higher salary mean all my income is taxed at a higher rate?",
        a: "No. Malaysia uses progressive bands, so each rate applies only to the part of your chargeable income that falls inside that band.",
      },
    ],
    relatedLinks: [
      { href: "/income-tax-calculator", label: "Income Tax Calculator" },
      { href: "/pcb-calculator", label: "PCB Calculator (MTD)" },
      { href: "/guides/tax-relief-2026-malaysia-ya-2025", label: "Tax Relief 2026: Full List" },
    ],
  },
  {
    slug: "how-to-check-epf-balance-statement",
    title: "How to Check Your EPF (KWSP) Balance & Statement",
    description:
      "The official ways to check your EPF balance and download your KWSP statement: the i-Akaun app, the i-Akaun website, a KWSP kiosk and the counter.",
    publishedDate: "2026-10-06",
    body: [
      "You can check your EPF (KWSP) balance and statement through i-Akaun, KWSP's online account, or in person at KWSP. You will see the balance for each of your three accounts: Akaun Persaraan, Akaun Sejahtera and Akaun Fleksibel.",
      "## Ways to check your EPF balance",
      "The table below lists the official options and what you need for each.",
      "## Can I check my EPF with just my IC number?",
      "Not on an ordinary website. Your balance is personal information, so the official online route needs an i-Akaun login, and the in-person route uses your MyKad. Be careful with third-party websites that ask for your IC number or personal details to \"check KWSP\".",
      "## Registering for i-Akaun for the first time",
      "Malaysian citizens and permanent residents can register through the KWSP i-Akaun app. You scan your MyKad, take a selfie to verify your identity (e-KYC), then create a user ID and password.",
      "## Downloading a statement",
      "On the i-Akaun website, open your account summary, choose the year you want and download the statement. Keep your statements: they are useful when you apply for a loan or plan your retirement.",
      "## Plan ahead with your balance",
      "Once you know your balance, use the EPF retirement calculator to project how it could grow with dividends until retirement.",
    ],
    table: {
      afterIndex: 2,
      caption: "Official ways to check your EPF balance",
      headers: ["Method", "What you need", "Note"],
      rows: [
        ["i-Akaun mobile app", "Smartphone and your MyKad (first-time registration)", "Balance of all three accounts"],
        ["i-Akaun website", "i-Akaun user ID and password", "Download statements by year"],
        ["KWSP self-service kiosk", "Your MyKad", "At KWSP branches"],
        ["KWSP counter", "Your identification", "Ask the staff for a statement"],
      ],
    },
    faq: [
      {
        q: "How do I check my KWSP balance?",
        a: "Log in to i-Akaun on the KWSP app or website, or use a KWSP self-service kiosk with your MyKad. You will see the balance of your Akaun Persaraan, Akaun Sejahtera and Akaun Fleksibel.",
      },
      {
        q: "Can I check my KWSP balance with only my IC number?",
        a: "Not through an official online channel. You need an i-Akaun login, or you can use a KWSP kiosk with your MyKad. Avoid third-party sites that ask for your IC number.",
      },
      {
        q: "How do I get my KWSP statement?",
        a: "Log in to the i-Akaun website, choose the year and download the statement, or ask for one at a KWSP kiosk or counter.",
      },
    ],
    relatedLinks: [
      { href: "/epf-retirement-calculator", label: "EPF Retirement & Dividend Calculator" },
      { href: "/epf-calculator", label: "EPF Calculator (KWSP)" },
      { href: "/epf-account-split-calculator", label: "EPF Account Split Calculator" },
    ],
  },
  {
    slug: "income-tax-number-tin-malaysia",
    title: "Income Tax Number (TIN) Malaysia: How to Find Yours",
    description:
      "What is your income tax number (TIN) in Malaysia? The IG format, how to check it on MyTax, and how to apply through e-Daftar if you do not have one.",
    publishedDate: "2026-10-06",
    body: [
      "Your income tax number is called the Tax Identification Number, or TIN (Nombor Pengenalan Cukai). LHDN uses it to identify you as a taxpayer, and you need it to file your income tax return.",
      "## What a TIN looks like",
      "For individuals, the TIN starts with the prefix IG, followed by numbers, up to 14 characters in total. The prefix IG replaces the older OG and SG prefixes, and the numbers stay the same.",
      "## Do I automatically have a TIN?",
      "LHDN registers TINs automatically for Malaysian citizens and permanent residents aged 18 and above, using data from the National Registration Department. Other people, such as those with no MyKad record, may need to apply.",
      "## How to find your TIN",
      "Log in to MyTax at mytax.hasil.gov.my and use the TIN search. You can also find it on the front page of your income tax return, or call the HASiL Contact Centre at 03-8911 1000 or visit an LHDN office.",
      "## How to apply for a TIN",
      "Since 1 January 2024, individuals who need a TIN apply online through e-Daftar on the MyTax portal.",
      "## Why it matters for your salary",
      "Employers use your TIN when they report your PCB (monthly tax deduction) to LHDN. To see how much tax your salary produces, use the income tax calculator.",
    ],
    faq: [
      {
        q: "What is the income tax number in Malaysia?",
        a: "It is the Tax Identification Number (TIN). For individuals it starts with IG followed by numbers, up to 14 characters in total.",
      },
      {
        q: "How do I check my TIN?",
        a: "Log in to MyTax at mytax.hasil.gov.my and use the TIN search. You can also find it on the front page of your income tax return or call the HASiL Contact Centre at 03-8911 1000.",
      },
      {
        q: "How do I apply for a TIN?",
        a: "Since 1 January 2024, individuals who need a TIN apply online through e-Daftar on the MyTax portal.",
      },
    ],
    relatedLinks: [
      { href: "/income-tax-calculator", label: "Income Tax Calculator" },
      { href: "/pcb-calculator", label: "PCB Calculator (MTD)" },
      { href: "/guides/tax-relief-2026-malaysia-ya-2025", label: "Tax Relief 2026: Full List" },
    ],
  },
];
